const relationLabelBuilders = {
  hosts: (item) => item.ip,
  users: (item) => item.user_name,
  services: (item) => item.service_name,
  rules: (item) => item.rule_name,
  policies: (item) => item.policy_name,
  requests: (item) => `Запрос №${item.request_id}`,
}

export const entityConfigs = [
  {
    key: 'users',
    title: 'Пользователи',
    route: 'users',
    eyebrow: 'Справочники',
    description: 'Учетные записи и их привязка к хостам.',
    createEnabled: true,
    deleteEnabled: true,
    filters: [
      { name: 'user_id', label: 'Номер пользователя', type: 'number' },
      { name: 'user_name', label: 'Имя', type: 'text' },
      { name: 'uid', label: 'UID', type: 'number' },
      { name: 'gid', label: 'GID', type: 'number' },
      {
        name: 'host_id',
        label: 'Хост',
        type: 'select',
        source: 'hosts',
        optionValueKey: 'host_id',
        getOptionLabel: relationLabelBuilders.hosts,
      },
    ],
    formFields: [
      { name: 'user_name', label: 'Имя пользователя', type: 'text', required: true },
      { name: 'uid', label: 'UID', type: 'number', required: true },
      { name: 'gid', label: 'GID', type: 'number', required: true },
      {
        name: 'host_id',
        label: 'Хост',
        type: 'select',
        source: 'hosts',
        optionValueKey: 'host_id',
        getOptionLabel: relationLabelBuilders.hosts,
        required: true,
      },
    ],
    columns: [
      { key: 'user_id', label: 'Номер' },
      { key: 'user_name', label: 'Имя' },
      { key: 'uid', label: 'UID' },
      { key: 'gid', label: 'GID' },
      {
        key: 'host_id',
        label: 'Хост',
        type: 'relation',
        source: 'hosts',
        optionValueKey: 'host_id',
        getOptionLabel: relationLabelBuilders.hosts,
      },
    ],
    detailFields: [
      { key: 'user_id', label: 'ID в базе' },
      { key: 'user_name', label: 'Имя пользователя' },
      { key: 'uid', label: 'UID' },
      { key: 'gid', label: 'GID' },
      {
        key: 'host_id',
        label: 'Хост',
        type: 'relation',
        source: 'hosts',
        optionValueKey: 'host_id',
        getOptionLabel: relationLabelBuilders.hosts,
      },
    ],
    getRecordId: (record) => record.user_id,
    getRecordKey: (record) => `user-${record.user_id}`,
    getDeleteLabel: (record) => `${record.user_name} (№${record.user_id})`,
  },
  {
    key: 'hosts',
    title: 'Хосты',
    route: 'hosts',
    eyebrow: 'Справочники',
    description: 'Список хостов для локальных пользователей.',
    createEnabled: true,
    deleteEnabled: true,
    filters: [
      { name: 'host_id', label: 'Номер хоста', type: 'number' },
      { name: 'ip', label: 'IP-адрес', type: 'text' },
    ],
    formFields: [{ name: 'ip', label: 'IP-адрес', type: 'text', required: true }],
    columns: [{ key: 'host_id', label: 'Номер' }, { key: 'ip', label: 'IP-адрес' }],
    detailFields: [
      { key: 'host_id', label: 'ID в базе' },
      { key: 'ip', label: 'IP-адрес' },
    ],
    getRecordId: (record) => record.host_id,
    getRecordKey: (record) => `host-${record.host_id}`,
    getDeleteLabel: (record) => record.ip,
  },
  {
    key: 'services',
    title: 'Сервисы',
    route: 'services',
    eyebrow: 'Справочники',
    description: 'Сервисы, для которых настраиваются правила доступа.',
    createEnabled: true,
    deleteEnabled: true,
    filters: [
      { name: 'service_id', label: 'Номер сервиса', type: 'number' },
      { name: 'service_name', label: 'Название', type: 'text' },
    ],
    formFields: [
      { name: 'service_name', label: 'Название сервиса', type: 'text', required: true },
    ],
    columns: [{ key: 'service_id', label: 'Номер' }, { key: 'service_name', label: 'Название сервиса' }],
    detailFields: [
      { key: 'service_id', label: 'ID в базе' },
      { key: 'service_name', label: 'Название сервиса' },
    ],
    getRecordId: (record) => record.service_id,
    getRecordKey: (record) => `service-${record.service_id}`,
    getDeleteLabel: (record) => record.service_name,
  },
  {
    key: 'rules',
    title: 'Правила',
    route: 'rules',
    eyebrow: 'Управление доступом',
    description: 'Условия доступа и итоговый эффект Allow/Deny.',
    createEnabled: true,
    deleteEnabled: true,
    filters: [
      { name: 'rule_id', label: 'Номер правила', type: 'number' },
      { name: 'rule_name', label: 'Название', type: 'text' },
      {
        name: 'effect',
        label: 'Эффект',
        type: 'triBoolean',
        allLabel: 'Любой эффект',
        trueFilterLabel: 'Разрешить',
        falseFilterLabel: 'Запретить',
      },
    ],
    formFields: [
      { name: 'rule_name', label: 'Название правила', type: 'text', required: true },
      {
        name: 'conditions',
        label: 'Условия (JSON)',
        type: 'json',
        required: true,
        rows: 12,
        helpText:
          'Список условий в JSON-массиве. Для справки используйте кнопку "Как описывать условия?"',
        showRuleHelp: true,
      },
      {
        name: 'effect',
        label: 'Разрешить доступ',
        type: 'boolean',
        booleanLabel: 'Allow',
      },
    ],
    columns: [
      { key: 'rule_id', label: 'Номер' },
      { key: 'rule_name', label: 'Название' },
      {
        key: 'effect',
        label: 'Эффект',
        type: 'boolean',
        trueLabel: 'Allow',
        falseLabel: 'Deny',
        trueVariant: 'success',
        falseVariant: 'danger',
      },
      { key: 'conditions', label: 'Условия', type: 'json' },
    ],
    detailFields: [
      { key: 'rule_id', label: 'ID в базе' },
      { key: 'rule_name', label: 'Название' },
      {
        key: 'effect',
        label: 'Эффект',
        type: 'boolean',
        trueLabel: 'Allow',
        falseLabel: 'Deny',
        trueVariant: 'success',
        falseVariant: 'danger',
      },
      { key: 'conditions', label: 'Условия', type: 'json' },
    ],
    getRecordId: (record) => record.rule_id,
    getRecordKey: (record) => `rule-${record.rule_id}`,
    getDeleteLabel: (record) => record.rule_name,
  },
  {
    key: 'policies',
    title: 'Политики',
    route: 'policies',
    eyebrow: 'Управление доступом',
    description: 'Политики, привязанные к конкретным пользователям.',
    createEnabled: true,
    deleteEnabled: true,
    filters: [
      { name: 'policy_id', label: 'Номер политики', type: 'number' },
      { name: 'policy_name', label: 'Название', type: 'text' },
      {
        name: 'user_id',
        label: 'Пользователь',
        type: 'select',
        source: 'users',
        optionValueKey: 'user_id',
        getOptionLabel: relationLabelBuilders.users,
      },
      {
        name: 'status',
        label: 'Статус',
        type: 'triBoolean',
        allLabel: 'Любой статус',
        trueFilterLabel: 'Включена',
        falseFilterLabel: 'Отключена',
      },
    ],
    formFields: [
      { name: 'policy_name', label: 'Название политики', type: 'text', required: true },
      {
        name: 'user_id',
        label: 'Пользователь',
        type: 'select',
        source: 'users',
        optionValueKey: 'user_id',
        getOptionLabel: relationLabelBuilders.users,
        required: true,
      },
      {
        name: 'status',
        label: 'Политика активна',
        type: 'boolean',
        booleanLabel: 'Активна',
      },
    ],
    columns: [
      { key: 'policy_id', label: 'Номер' },
      { key: 'policy_name', label: 'Название' },
      {
        key: 'user_id',
        label: 'Пользователь',
        type: 'relation',
        source: 'users',
        optionValueKey: 'user_id',
        getOptionLabel: relationLabelBuilders.users,
        linkTo: (value) => `/users?user_id=${value}`,
      },
      {
        key: 'status',
        label: 'Статус',
        type: 'boolean',
        trueLabel: 'Активна',
        falseLabel: 'Отключена',
        trueVariant: 'success',
        falseVariant: 'secondary',
      },
    ],
    detailFields: [
      { key: 'policy_id', label: 'ID в базе' },
      { key: 'policy_name', label: 'Название' },
      {
        key: 'user_id',
        label: 'Пользователь',
        type: 'relation',
        source: 'users',
        optionValueKey: 'user_id',
        getOptionLabel: relationLabelBuilders.users,
        linkTo: (value) => `/users?user_id=${value}`,
      },
      {
        key: 'status',
        label: 'Статус',
        type: 'boolean',
        trueLabel: 'Активна',
        falseLabel: 'Отключена',
        trueVariant: 'success',
        falseVariant: 'secondary',
      },
    ],
    getRecordId: (record) => record.policy_id,
    getRecordKey: (record) => `policy-${record.policy_id}`,
    getDeleteLabel: (record) => record.policy_name,
  },
  {
    key: 'policyContents',
    title: 'Привязки правил',
    route: 'policy-contents',
    eyebrow: 'Управление доступом',
    description: 'Соответствия: политика → сервис → правило.',
    createEnabled: true,
    deleteEnabled: true,
    filters: [
      {
        name: 'policy_id',
        label: 'Политика',
        type: 'select',
        source: 'policies',
        optionValueKey: 'policy_id',
        getOptionLabel: relationLabelBuilders.policies,
      },
      {
        name: 'service_id',
        label: 'Сервис',
        type: 'select',
        source: 'services',
        optionValueKey: 'service_id',
        getOptionLabel: relationLabelBuilders.services,
      },
      {
        name: 'rule_id',
        label: 'Правило',
        type: 'select',
        source: 'rules',
        optionValueKey: 'rule_id',
        getOptionLabel: relationLabelBuilders.rules,
      },
    ],
    formFields: [
      {
        name: 'policy_id',
        label: 'Политика',
        type: 'select',
        source: 'policies',
        optionValueKey: 'policy_id',
        getOptionLabel: relationLabelBuilders.policies,
        required: true,
      },
      {
        name: 'service_id',
        label: 'Сервис',
        type: 'select',
        source: 'services',
        optionValueKey: 'service_id',
        getOptionLabel: relationLabelBuilders.services,
        required: true,
      },
      {
        name: 'rule_id',
        label: 'Правило',
        type: 'select',
        source: 'rules',
        optionValueKey: 'rule_id',
        getOptionLabel: relationLabelBuilders.rules,
        required: true,
      },
    ],
    columns: [
      { key: 'policy_id', label: 'Номер политики' },
      {
        key: 'policy_id',
        label: 'Политика',
        type: 'relation',
        source: 'policies',
        optionValueKey: 'policy_id',
        getOptionLabel: relationLabelBuilders.policies,
        linkTo: (value) => `/policies?policy_id=${value}`,
      },
      {
        key: 'service_id',
        label: 'Сервис',
        type: 'relation',
        source: 'services',
        optionValueKey: 'service_id',
        getOptionLabel: relationLabelBuilders.services,
        linkTo: (value) => `/services?service_id=${value}`,
      },
      {
        key: 'rule_id',
        label: 'Правило',
        type: 'relation',
        source: 'rules',
        optionValueKey: 'rule_id',
        getOptionLabel: relationLabelBuilders.rules,
        linkTo: (value) => `/rules?rule_id=${value}`,
      },
    ],
    detailFields: [
      { key: 'policy_id', label: 'Policy ID' },
      { key: 'service_id', label: 'Service ID' },
      { key: 'rule_id', label: 'Rule ID' },
    ],
    getRecordId: (record) => ({
      policy_id: record.policy_id,
      service_id: record.service_id,
    }),
    getRecordKey: (record) => `policy-content-${record.policy_id}-${record.service_id}`,
    getDeleteLabel: (record) =>
      `policy №${record.policy_id}, service №${record.service_id}`,
  },
  {
    key: 'requests',
    title: 'Журнал запросов',
    route: 'requests',
    eyebrow: 'Аудит',
    description: 'События, по которым система принимала решение о доступе.',
    createEnabled: false,
    deleteEnabled: true,
    filters: [
      { name: 'request_id', label: 'Номер запроса', type: 'number' },
      {
        name: 'user_id',
        label: 'Пользователь',
        type: 'select',
        source: 'users',
        optionValueKey: 'user_id',
        getOptionLabel: relationLabelBuilders.users,
      },
    ],
    formFields: [
      {
        name: 'user_id',
        label: 'Пользователь',
        type: 'select',
        source: 'users',
        optionValueKey: 'user_id',
        getOptionLabel: relationLabelBuilders.users,
        nullable: true,
      },
      {
        name: 'context',
        label: 'Контекст (JSON)',
        type: 'json',
        required: true,
        rows: 12,
      },
    ],
    columns: [
      { key: 'request_id', label: 'Номер' },
      {
        key: 'user_id',
        label: 'Пользователь',
        type: 'relation',
        source: 'users',
        optionValueKey: 'user_id',
        getOptionLabel: relationLabelBuilders.users,
        linkTo: (value) => `/users?user_id=${value}`,
      },
      {
        key: '_policyLink',
        label: 'Политика',
        type: 'link',
        getLabel: (row) => (row.user_id ? 'Открыть политику' : '—'),
        getLink: (row) => (row.user_id ? `/policies?user_id=${row.user_id}` : ''),
      },
      { key: 'timestamp', label: 'Время', type: 'date' },
      { key: 'context', label: 'Контекст', type: 'json' },
    ],
    detailFields: [
      { key: 'request_id', label: 'ID в базе' },
      {
        key: 'user_id',
        label: 'Пользователь',
        type: 'relation',
        source: 'users',
        optionValueKey: 'user_id',
        getOptionLabel: relationLabelBuilders.users,
        linkTo: (value) => `/users?user_id=${value}`,
      },
      { key: 'timestamp', label: 'Время', type: 'date' },
      { key: 'context', label: 'Контекст', type: 'json' },
    ],
    getRecordId: (record) => record.request_id,
    getRecordKey: (record) => `request-${record.request_id}`,
    getDeleteLabel: (record) => `Запрос №${record.request_id}`,
  },
  {
    key: 'decisions',
    title: 'Журнал решений',
    route: 'decisions',
    eyebrow: 'Аудит',
    description: 'Результаты проверки доступа с указанием policy и result.',
    createEnabled: false,
    deleteEnabled: true,
    filters: [
      { name: 'decision_id', label: 'Номер решения', type: 'number' },
      {
        name: 'request_id',
        label: 'Запрос',
        type: 'select',
        source: 'requests',
        optionValueKey: 'request_id',
        getOptionLabel: relationLabelBuilders.requests,
      },
      {
        name: 'policy_id',
        label: 'Политика',
        type: 'select',
        source: 'policies',
        optionValueKey: 'policy_id',
        getOptionLabel: relationLabelBuilders.policies,
      },
      {
        name: 'result',
        label: 'Результат',
        type: 'triBoolean',
        allLabel: 'Любой результат',
        trueFilterLabel: 'Разрешено',
        falseFilterLabel: 'Запрещено',
      },
    ],
    formFields: [
      {
        name: 'request_id',
        label: 'Запрос',
        type: 'select',
        source: 'requests',
        optionValueKey: 'request_id',
        getOptionLabel: relationLabelBuilders.requests,
        required: true,
      },
      {
        name: 'policy_id',
        label: 'Политика',
        type: 'select',
        source: 'policies',
        optionValueKey: 'policy_id',
        getOptionLabel: relationLabelBuilders.policies,
        nullable: true,
      },
      {
        name: 'result',
        label: 'Разрешить доступ',
        type: 'boolean',
        booleanLabel: 'Allow',
      },
    ],
    columns: [
      { key: 'decision_id', label: 'Номер' },
      {
        key: 'request_id',
        label: 'Запрос',
        type: 'relation',
        source: 'requests',
        optionValueKey: 'request_id',
        getOptionLabel: relationLabelBuilders.requests,
        linkTo: (value) => `/requests?request_id=${value}`,
      },
      {
        key: 'policy_id',
        label: 'Политика',
        type: 'relation',
        source: 'policies',
        optionValueKey: 'policy_id',
        getOptionLabel: relationLabelBuilders.policies,
        linkTo: (value) => `/policy-contents?policy_id=${value}`,
      },
      {
        key: 'result',
        label: 'Результат',
        type: 'boolean',
        trueLabel: 'Allow',
        falseLabel: 'Deny',
        trueVariant: 'success',
        falseVariant: 'danger',
      },
      { key: 'timestamp', label: 'Время', type: 'date' },
    ],
    detailFields: [
      { key: 'decision_id', label: 'ID в базе' },
      {
        key: 'request_id',
        label: 'Запрос',
        type: 'relation',
        source: 'requests',
        optionValueKey: 'request_id',
        getOptionLabel: relationLabelBuilders.requests,
        linkTo: (value) => `/requests?request_id=${value}`,
      },
      {
        key: 'policy_id',
        label: 'Политика',
        type: 'relation',
        source: 'policies',
        optionValueKey: 'policy_id',
        getOptionLabel: relationLabelBuilders.policies,
        linkTo: (value) => `/policy-contents?policy_id=${value}`,
      },
      {
        key: 'result',
        label: 'Результат',
        type: 'boolean',
        trueLabel: 'Allow',
        falseLabel: 'Deny',
        trueVariant: 'success',
        falseVariant: 'danger',
      },
      { key: 'timestamp', label: 'Время', type: 'date' },
    ],
    getRecordId: (record) => record.decision_id,
    getRecordKey: (record) => `decision-${record.decision_id}`,
    getDeleteLabel: (record) => `Решение №${record.decision_id}`,
  },
]
