services:

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend

  clipe_db:
    image: postgres:15
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: clipe
    command: postgres -c timezone=Europe/Moscow
    ports:
      - ":5432"
    volumes:
      - clipe_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  nginx:
    build: ./nginx
    depends_on:
      - api
      - decision
      - panel
    ports:
      - "443:443"
    volumes:
      - ../tls:/etc/nginx/tls:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

  api:
    build: ./api
    depends_on:
      - clipe_db
    env_file:
      - .env
    ports:
      - ":8080"
    networks:
      - backend

  decision:
    build: ./decision
    depends_on:
      - clipe_db
    env_file:
      - .env
    ports:
      - ":8080"
    networks:
      - backend
  
  panel:
    build: ./panel
    #command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - api
      - decision
    networks:
      - backend

volumes:
  clipe_db_data:
  pgadmin_data:

networks:
  backend:
    driver: bridge